void swap(double& a, double& b);
int partition(double arr[], long low, long high);
void quickSort(double arr[], long low, long high);
double max(double values[], long valuesLen);
double sum(double values[], long valuesLen);
double mean(double values[], long valuesLen);
double meanSquare(double values[], long valuesLen);
double variance(double values[], long valuesLen);
long firstInfIndex(double table[], long tableLen, double value);
void discretFourierTransform(double modules[], double angles[], double signals[], long signalsLen);
